@startuml
skinparam packageStyle rectangle

package "Utils" {
    [JavaUtils]
    [SpringUtils]
    [SpringMvcUtils]
    [SpringWebfluxUtils]

    [SpringUtils] --> [JavaUtils]
    [SpringMvcUtils] --> [SpringUtils]
    [SpringWebfluxUtils] --> [SpringUtils]
    [SpringMvcUtils] --> [api-model]
}

package "API" {
    [api-model]
    [api-model] --> [JavaUtils]
}

package "Gateway" {
    [gateways]
    [gateways] --> [SpringWebfluxUtils]
    [gateways] --> [api-model]
}

package "Base" {
    [netty-socket]

    [oss-service]

    [netty-socket] --> [SpringUtils]
    [netty-socket] --> [api-model]

    [oss-service] --> [SpringMvcUtils]
    [oss-service] --> [api-model]
}

package "offline" {
    [recommend-offline-service]

    [recommend-offline-service] --> [SpringUtils]
    [recommend-offline-service] --> [api-model]
}

package "Business" {
    [auth-service]
    [user-service]
    [sms-service]
    [message-service]
    [relationship-service]
    [post-service]
    [search-service]
    [feature-service]

    [recommend-service]

    [search-service] --> [SpringUtils]
    [search-service] --> [api-model]

    [auth-service] --> [SpringWebfluxUtils]
    [auth-service] --> [api-model]

    [user-service] --> [SpringWebfluxUtils]
    [user-service] --> [api-model]

    [sms-service] --> [SpringWebfluxUtils]
    [sms-service] --> [api-model]

    [message-service] --> [SpringMvcUtils]
    [message-service] --> [api-model]

    [relationship-service] --> [SpringWebMvcUtils]
    [relationship-service] --> [api-model]

    [post-service] --> [SpringMvcUtils]
    [post-service] --> [api-model]

    [recommend-service] --> [SpringUtils]
    [recommend-service] --> [api-model]

    [feature-service] --> [SpringMvcUtils]
    [feature-service] --> [api-model]
}

@enduml