@startuml
skinparam packageStyle rectangle


package "Base" {
    [netty-socket]
    [oss-service]
}

package "Business" {
    [user-relationship-service]
    [auth-sms-service]
    [message-service]
    [post-service]
    [recommend-service]
    [search-service]
    [feature-service]

    [message-service] --> [user-relationship-service]
    [message-service] -[#0000FF]--> [oss-service]
    [message-service] -[#0000FF]--> [netty-socket]

    [user-relationship-service] --> [auth-sms-service]

    [post-service] --> [user-relationship-service]
    [post-service] -[#0000FF]--> [oss-service]

    [recommend-service] --> [user-relationship-service]
    [recommend-service] --> [post-service]
}

package "Gateway" {
    [gateways]

    [gateways] --> [auth-sms-service]
}

@enduml